# Generated by Django 4.0.5 on 2022-08-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPRESS',
            fields=[
                ('cod', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('tipSeg', models.CharField(max_length=20)),
            ],
        ),
    ]
