# Generated by Django 4.0.5 on 2022-08-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apPat', models.CharField(max_length=20)),
                ('apMat', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apPat', models.CharField(max_length=20)),
                ('apMat', models.CharField(max_length=20)),
                ('nColMed', models.CharField(max_length=20)),
            ],
        ),
    ]
