# Generated by Django 4.0.5 on 2022-08-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
