# Generated by Django 4.0.5 on 2022-07-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPRESS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=20)),
                ('tipSeg', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=20)),
                ('apPat', models.CharField(max_length=20)),
                ('apMat', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=20)),
                ('apPat', models.CharField(max_length=20)),
                ('apMat', models.CharField(max_length=20)),
                ('nColMed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=20)),
                ('apPat', models.CharField(max_length=20)),
                ('telf', models.CharField(max_length=6)),
                ('edad', models.IntegerField(max_length=2)),
                ('dir', models.CharField(max_length=6)),
                ('fechNac', models.DateField()),
            ],
        ),
    ]
