# Generated by Django 4.0.5 on 2022-08-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_remove_ipress_id_remove_jefe_id_remove_medico_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dir',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
