# Generated by Django 4.0.5 on 2022-08-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_alter_paciente_dir_alter_paciente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='apMat',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
