# Generated by Django 4.0.5 on 2022-08-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_paciente_apmat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
