# Generated by Django 4.0.5 on 2022-08-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_delete_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apPat', models.CharField(max_length=20)),
                ('apMat', models.CharField(max_length=20)),
                ('telf', models.CharField(max_length=6)),
                ('edad', models.IntegerField()),
                ('dir', models.CharField(max_length=30)),
                ('fechNac', models.DateField()),
            ],
        ),
    ]
