# Generated by Django 4.0.5 on 2022-08-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
