# Generated by Django 4.0.5 on 2022-08-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0009_paciente_medico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPRESS',
        ),
        migrations.DeleteModel(
            name='Jefe',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medico',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
